### ISSUE TITLE
After ejecting, there is an error says 'No PostCSS Config found'

### ISSUE THREAD

**Issue by joshua7v** [just-boris/react-app-styleguidist#2]
I want to change the port, but can't figure out the right way.
so i ran the eject command, removed the react-app-styleguidist package and installed react-styleguidist instead. And here comes the error.

```shell
ERROR in ./~/css-loader?importLoaders=1!./~/postcss-loader!./src/index.css
Module build failed: Error: No PostCSS Config found in: ...../src
    at ...../node_modules/postcss-load-config/index.js:51:26
 @ ./src/index.css 4:14-130 13:2-17:4 14:20-136

ERROR in ./~/css-loader?importLoaders=1!./~/postcss-loader!./src/components/App.css
Module build failed: Error: No PostCSS Config found in: ...../src/components
    at ...../node_modules/postcss-load-config/index.js:51:26
 @ ./src/components/App.css 4:14-134 13:2-17:4 14:20-140
```

**Comment by just-boris** [comment]
Seems like recent updates in `create-react-app` had caused this.

Could you tell me version of `react-scripts` and `react-styleguidist` that you have?

**Comment by joshua7v** [comment]
in my package.json

"react-scripts": "0.9.5"
"react-styleguidist": "^4.6.3"
